
campaign = 'kaiu-wall'
author_id = '99effb885d9911e09da140403656340d'
campaign_id = '9ea9185aacf211e5adf722000aea131a'


[oauth]
token = 'jfnr2sUWKkQ7Y2cyhcy0'
app_token = 'fNMYfvoIMBBpMJtI9mpz'


[ranks]
4 = 'Corporal'
5 = 'Squad Sergeant'
6 = 'Platoon Lieutenant'
7 = 'Company Captain'
8 = 'Battalion Commander'


[rank_xp_bases]
4 = 50
6 = 100
7 = 150


[clans]
# These numbers are specific to the 3rd Imperial Legion and aren't valid elsewhere.
# The figures in all other sections are mostly accurate for the Empire overall.
lion = 40
dragon = 25
phoenix = 25
imperial = 5
crab = 1
unicorn = 1
crane = 1
scorpion = 1
minor = 1


[clan]

[[lion]]
matsu = 275
akodo = 150
ikoma = 50
kitsu = 25

[[dragon]]
mirumoto = 125
togashi = 20
kitsuki = 15
agasha = 15

[[phoenix]]
shiba = 100
isawa = 60
asoko = 15

[[imperial]]
seppun = 45
hantei = 15
otomo = 10
miya = 5

[[minor]]
gusai = 30
tonbo = 15
suzume = 5
kitsune = 5
ashinagabachi = 5

[[crab]]
hida = 175
yasuki = 75
kaiu = 25
kuni = 15
hiruma = 10

[[unicorn]]
shinjo = 75
moto = 75
otaku = 40
ide = 20
iuchi = 15

[[crane]]
doji = 100
daidoji = 90
kakita = 75
asahina = 10

[[scorpion]]
bayushi = 125
shosuro = 80
soshi = 15
yogo = 5


[schools]

[[default]]
bushi = 80
merchant = 10
courtier = 10

[[lion]]
akodo_bushi = 40
matsu_bushi = 40
ikoma_bard = 10
merchant = 5
courtier = 5

[[dragon]]
mirumoto_bushi = 60
kitsuki_magistrate = 14
togashi_ise_zumi = 1
courtier = 10
merchant = 10

[[phoenix]]
shiba_bushi = 44
isawa_bushi = 35
isawa_ishi = 1
courtier = 10
merchant = 10

[[crab]]
hida_bushi = 60
hiruma_bushi = 20
merchant = 15
courtier = 5

[[unicorn]]
shinjo_bushi = 40
otaku_bushi = 30
ide_diplomat = 10
courtier = 10
merchant = 10

[[crane]]
kakita_bushi = 35
daidoji_bushi = 30
doji_artisan = 10
merchant = 10
courtier = 15

[[scorpion]]
bayushi_bushi = 55
yogo_bushi = 15
shosuro_actor = 5
merchant = 10
courtier = 15

